### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by tomvars** [pydicom/pylibjpeg-rle#13]
Hi,

I run into this

`ImportError: dlopen(/Users/tom/.asdf/installs/python/3.8.10/lib/python3.8/site-packages/rle/_rle.cpython-38-darwin.so, 0x0002): tried: '/Users/tom/.asdf/installs/python/3.8.10/lib/python3.8/site-packages/rle/_rle.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))`

When using `pydicom` on an M1 macbook. Any suggestions for how to fix it would be appreciated!

Thanks

**Comment by scaramallion** [comment]
Hmm, I'd need to add wheels for M1. If you need a workaround [you can install the source and compile](https://github.com/pydicom/pylibjpeg-rle#installing-the-development-version) (although I can't guarantee it'll work out of the box).

**Comment by tomvars** [comment]
Thanks for your reply, installing `pylibjpeg-rle` from source, then installing `pydicom` from source works on my 2021 Apple M1 Pro 👍
