### ISSUE TITLE
Installing this dependency in a docker container always fails

### ISSUE THREAD

**Issue by AlexanderProd** [pydicom/pylibjpeg-rle#14]
I have a project wich has this library as dependency and I want to dockerize it but the `pip install` step always crashes. 

I'm always getting this error when trying to build my container. I'm installing all the packages in the container which I think could be necessary but i think there must be still something missing. 

This is my `Dockerfile`:

```
FROM python:3.8

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y gcc g++ git cmake curl make apt-transport-https ca-certificates build-essential libc-dev python3-dev libsasl2-dev libldap2-dev libssl-dev libsnmp-dev libjpeg-dev zlib1g-dev libatlas-base-dev libffi-dev && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD "uwsgi -s /tmp/flaskr.sock --manage-script-name --mount /=flaskr:app"
```

Python, git and Rust are installed I'd like to to know what else I'm missing.

Thank you!

**Comment by scaramallion** [comment]
What's the output for `pip install`?

**Comment by AlexanderProd** [comment]
```
executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements.txt]: exit code: 1
```

**Comment by scaramallion** [comment]
Could you try again with `pip install -v`?

**Comment by AlexanderProd** [comment]
> Could you try again with `pip install -v`?

Sure: 

```
 > [5/6] RUN pip install -v:
#10 1.355 Using pip 22.0.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
#10 1.393 ERROR: You must give at least one requirement to install (see "pip help install")
#10 1.490 WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
#10 1.490 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install -v]: exit code: 1
```

**Comment by scaramallion** [comment]
Sorry, I meant adding `-v` to your existing `pip` command

**Comment by AlexanderProd** [comment]
> Sorry, I meant adding `-v` to your existing `pip` command

`RUN pip install --no-cache-dir -v -r requirements.txt`

Not much different: 
```
#10 140.8   Building wheel for uWSGI (setup.py): finished with status 'done'
#10 140.8   Created wheel for uWSGI: filename=uWSGI-2.0.20-cp38-cp38-linux_aarch64.whl size=577929 sha256=b707dd76b052dc6110eacebe6265b95889581c15ac1a3d396b85585a5dac17ad
#10 140.8   Stored in directory: /tmp/pip-ephem-wheel-cache-2loer4st/wheels/cb/4d/54/002a215100a8c4e125654600f0a4304dae742442ddc4ba6ea1
#10 140.8 Successfully built pylibjpeg-openjpeg pylibjpeg-rle uWSGI
#10 140.8 Failed to build pylibjpeg-libjpeg
#10 140.8 ERROR: Could not build wheels for pylibjpeg-libjpeg, which is required to install pyproject.toml-based projects
#10 141.0 WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
#10 141.0 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install --no-cache-dir -v -r requirements.txt]: exit code: 1
```

**Comment by AlexanderProd** [comment]
I've also added `ENV PATH="/root/.cargo/bin:${PATH}"` to my dockerfile since some people recommend that but no luck.

**Comment by AlexanderProd** [comment]
Strangely enough I'm able to build the container on my Ubuntu 18.04 server, until now I've only tried it on my M1 Pro MacBook running 12.3.1

Docker desktop on my macbook is v4.8.1 and engine v20.10.14

**Comment by scaramallion** [comment]
That last `pip` output said it was successfully built, just `pylibjpeg-libjpeg` that's failing, which doesn't surprise me for M1 since it's probably missing some compiler flags that might be needed for building on the new arch.

**Comment by AlexanderProd** [comment]
> That last `pip` output said it was successfully built, just `pylibjpeg-libjpeg` that's failing, which doesn't surprise me for M1 since it's probably missing some compiler flags that might be needed for building on the new arch.

but I can use it perfectly outside of docker on my M1

**Comment by scaramallion** [comment]
Hmm, can you try `pip install -vv pylibjpeg-libjpeg` with the double `-vv` flag? I'd really like to see the actual build fault

**Comment by AlexanderProd** [comment]
> Hmm, can you try `pip install -vv pylibjpeg-libjpeg` with the double `-vv` flag? I'd really like to see the actual build fault

This is the last output from this command. 

```
#10 12.69   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilibjpeg/src/libjpeg -Ilibjpeg/src/interface -I/tmp/pip-build-env-k778g4df/overlay/lib/python3.8/site-packages/numpy/core/include -I/usr/local/include/python3.8 -I/usr/local/include/python3.8 -c libjpeg/_libjpeg.cpp -o build/temp.linux-aarch64-3.8/libjpeg/_libjpeg.o -DUSE_AUTOCONF -mfpmath=387
#10 12.69   gcc: error: unrecognized command-line option ‘-mfpmath=387’
#10 12.69   error: command '/usr/bin/gcc' failed with exit code 1
#10 12.70   error: subprocess-exited-with-error
#10 12.70   
#10 12.70   × Building wheel for pylibjpeg-libjpeg (pyproject.toml) did not run successfully.
#10 12.70   │ exit code: 1
#10 12.70   ╰─> See above for output.
#10 12.70   
#10 12.70   note: This error originates from a subprocess, and is likely not a problem with pip.
#10 12.70   full command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp8u5aqn4u
#10 12.70   cwd: /tmp/pip-install-0u4b63jv/pylibjpeg-libjpeg_6168641b8505444f90da1fbe4c7e3c0c
#10 12.70   Building wheel for pylibjpeg-libjpeg (pyproject.toml): finished with status 'error'
#10 12.70   ERROR: Failed building wheel for pylibjpeg-libjpeg
#10 12.70 Failed to build pylibjpeg-libjpeg
#10 12.70 ERROR: Could not build wheels for pylibjpeg-libjpeg, which is required to install pyproject.toml-based projects
#10 12.70 Exception information:
#10 12.70 Traceback (most recent call last):
#10 12.70   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
#10 12.70     status = run_func(*args)
#10 12.70   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#10 12.70     return func(self, options, args)
#10 12.70   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 375, in run
#10 12.70     raise InstallationError(
#10 12.70 pip._internal.exceptions.InstallationError: Could not build wheels for pylibjpeg-libjpeg, which is required to install pyproject.toml-based projects
#10 12.76 WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
#10 12.76 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#10 12.76 Removed build tracker: '/tmp/pip-req-tracker-2x202sk_'
------
executor failed running [/bin/sh -c pip install -vv pylibjpeg-libjpeg]: exit code: 1
```

**Comment by scaramallion** [comment]
`‘-mfpmath=387’`

Looks like the compiler flag doesn't exist for M1

**Comment by AlexanderProd** [comment]
But when install the package outside of docker with pip it would still need to be built right? Or does it use prebuilt binaries for M1? 

Because I can install it perfectly on my M1 outside of docker.

**Comment by scaramallion** [comment]
Sorry! Been busy. When you compile outside of docker is it using `clang` or `gcc`?

**Comment by scaramallion** [comment]
Sorry, you're right. I think the configuration step isn't picking up that the `mfpmath` compiler flag is unavailable under docker and is adding it.

Can you test to see what happens if you compile [libjpeg](https://github.com/thorfdbg/libjpeg) directly in docker?

**Comment by AlexanderProd** [comment]
I first built [libjpeg](https://github.com/thorfdbg/libjpeg) directly on my M1 Mac to see if I could even build it.

```
./configure --prefix=/tmp/jpeg-build
make 
make install 
```

and It was successful, I can run the outputted `jpeg` binary. 

Then I tried to build it inside a docker container using the following `Dockerfile`. 

```
FROM python:3.8

WORKDIR /usr/src/jpeg-build

RUN apt-get update && \
    apt-get install -y gcc g++ git cmake curl make apt-transport-https ca-certificates build-essential libc-dev libsasl2-dev libldap2-dev libssl-dev libsnmp-dev libjpeg-dev zlib1g-dev libatlas-base-dev libffi-dev

RUN git clone https://github.com/thorfdbg/libjpeg && \
    cd libjpeg && \
    ./configure --prefix=/usr/src/jpeg-build && \
    make && \
    make install

ENTRYPOINT [ "/usr/src/jpeg-build/libjpeg/jpeg" ]
```
and it worked fine too, when running the container I get the default output when running `jpeg`.

**Comment by scaramallion** [comment]
Welp. OK I need to think about it a bit more. There's really not much difference between how `pylibjpeg-libjpeg` builds and plain old `libjpeg`.

**Comment by scaramallion** [comment]
I've updated the version of libjpeg used, do you mind trying to build from the [current master](https://github.com/pydicom/pylibjpeg-libjpeg)?

**Comment by AlexanderProd** [comment]
Yup installing `pylibjpeg-libjpeg` from the current master works now! Are you going to release a new version to PyPi too?

**Comment by jackpaparian** [comment]
I'm also affected by this issue (`unrecognized command-line option ‘-mfpmath=387’` on M1), and installing from the current master resolves the problem.

@scaramallion when do you plan to release a new version to PyPI?
